### ISSUE TITLE
python3 board.py throws an error

### ISSUE THREAD

**Issue by hawkoon** [cnsr/tornado_imageboard#70]
> root@localhost:/home/tornado_imageboard# python3 board.py
> Traceback (most recent call last):
>   File "board.py", line 745, in <module>
>     main()
>   File "board.py", line 737, in main
>     latest_postnumber = latest_db['posts'].find({}).sort('count', -1)[0]['count']
>   File "/usr/local/lib/python3.7/dist-packages/pymongo/cursor.py", line 616, in __getitem__
>     raise IndexError("no such item for Cursor instance")
> IndexError: no such item for Cursor instance

**Comment by hawkoon** [comment]
Using python instead of python3 throws this:

>  python board.py
>   File "board.py", line 72
>     async def roll(subject):
>             ^
> SyntaxError: invalid syntax

**Comment by cnsr** [comment]
I'll look into it asap

**Comment by cnsr** [comment]
Issue fixed, thanks for notifying.
In any case, this project is not being actively maintained and contains a lot of poorly written code since it was one of my first takes into python development.
Issues might (and will) pop up here and there, please notify me of them.
